const CourseActionTypes = {
    FETCH_COURSES_REQUEST: "FETCH_COURSES_REQUEST",
    FETCH_COURSES_SUCCESS: "FETCH_COURSES_REQUEST",
    FETCH_COURSES_FAIL: "FETCH_COURSES_REQUEST",
    TOGGLE_WISHLIST: "TOGGLE_WISHLIST",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    TOGGLE_THEME: "TOGGLE_THEME"
};

export default CourseActionTypes;
