const ActionTypes = {
  SHOW_SIGNIN_MODAL: "SHOW_SIGNIN_MODAL",
  CLOSE_SIGNIN_MODAL: "CLOSE_SIGNIN_MODAL",
  SHOW_SIGNUP_MODAL: "SHOW_SIGNUP_MODAL",
  CLOSE_SIGNUP_MODAL: "CLOSE_SIGNUP_MODAL"
};

export default ActionTypes;
